# Generated by Django 6.1 on 2026-08-20 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('apartment', 'شقة'), ('villa', 'فيلا'), ('chalet', 'شاليه'), ('summer', 'مصيف'), ('property', 'عقار')], default='property', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('cairo', 'القاهرة'), ('giza', 'الجيزة'), ('north_coast', 'الساحل الشمالي'), ('hurghada', 'الغردقة'), ('dahab', 'دهب'), ('sharm', 'شرم الشيخ'), ('ain_sokhna', 'العين السخنة')], max_length=30),
        ),
    ]
