# Generated by Django 6.1 on 2026-08-23 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_category_alter_property_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('available', models.BooleanField(default=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dates', to='properties.property')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('property', 'date')},
            },
        ),
    ]
