# Generated by Django 6.1 on 2026-08-24 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='propertydate',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='property',
            name='guests',
        ),
        migrations.AlterField(
            model_name='booking',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='booking',
            name='id_card',
            field=models.ImageField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'قيد المراجعة'), ('confirmed', 'تم التأكيد'), ('cancelled', 'ملغي')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='property',
            name='category',
            field=models.CharField(choices=[('apartment', 'شقق'), ('villa', 'فلل'), ('chalet', 'شاليهات'), ('summer', 'مصايف'), ('property', 'عقارات')], max_length=30),
        ),
        migrations.AlterField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='properties/'),
        ),
        migrations.AlterField(
            model_name='property',
            name='location',
            field=models.CharField(choices=[('cairo', 'القاهرة'), ('giza', 'الجيزة'), ('north_coast', 'الساحل الشمالي'), ('hurghada', 'الغردقة'), ('dahab', 'دهب'), ('sharm', 'شرم الشيخ'), ('ain_sokhna', 'العين السخنة')], max_length=50),
        ),
    ]
